### ISSUE TITLE
Add user db/root to icat.server's rootUserNames

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject-contrib/icat-ansible#15]
The test suite for icat.client expects the 'db/root' user to have permission to create a Facility. This would usually only be possible when logged in as the administrator. Therefore we need to add 'db/root' the 'rootUserNames' field of the icat.server run.properties file (and reinstall icat.server).

**Comment by MRichards99** [comment]
This is done when the DB authenticator role is run (thanks to #75)
