### ISSUE TITLE
Upgrade icat component versions

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject-contrib/icat-ansible#16]
Upgrade versions:
icat.server 4.10.0
topcat 2.4.5? (soon)
ids?

**Comment by stuartpullinger** [comment]
Would need to run the database upgrade script if upgrading from 4.9.1 to 4.10.0 - but only on a system which already has 4.9.1 installed. Perhaps these ansible scripts assume a fresh system...

**Comment by MRichards99** [comment]
Closing as this is an old issue
