### ISSUE TITLE
Check version number when deciding whether to install

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject-contrib/icat-ansible#29]
Currently, roles check for the existence of a directory under ~/install to decide whether to unzip the recently-downloaded component or not. If the directory exists, the unzip step is skipped. For example, see the icat.server step [here](https://github.com/icatproject-contrib/icat-ansible/blob/master/roles/icat-server/tasks/main.yml#L22).

This behaviour prevents the component being upgraded when the version number is updated: the directory already exists so the upgraded component is never unzipped. Instead, the role should check the version number stored in the local fact file and unzip if the current version is different. [Here](https://github.com/icatproject-contrib/icat-ansible/blob/master/roles/icat-server/tasks/installation.yml#L18) is where the icat server version number is set at the end of the installation.

When unzipping the new component in-place, the new configuration files (eg. `setup.properties.example`) will overwrite the old configuration files. However, the component `.war` file contains the version number in its file name so will be unzipped alongside the old `.war` file. The installation script will fail if there is more than one `.war` file. So, in addition to unzipping the new component, the role will have to remove the old `.war` file or delete the old directory.

To delete the entire installation directory before unzipping the new component feels like the ansible way - being idempotent and all - but also a bit risky in a real production environment. I'm not sure if I am brave enough for this approach. Alternatively, since we will know the currently installed version number from the local fact file, we should be able to delete the `.war` file directly.

**Comment by stuartpullinger** [comment]
@louise-davies and @ibbythedridi : What do you think?

**Comment by louise-davies** [comment]
@stuartpullinger I think deleting the old war directly is fine. Like you say, it doesn't affect the other configuration files in a pure "upgrade component but don't modify config" run which is probably a better use case for production upgrades.

**Comment by louise-davies** [comment]
@stuartpullinger I have something for this working, however, for icat.server specifically, a simple auto upgrade like this may still fail if there are DB migrations to be done. #4 raises this issue, but I don't know how we go about solving it. I think the only way is for the database migrations to be left as a manual step. Thoughts?
