### ISSUE TITLE
Can icat-ansible run the schema upgrade scripts?

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject-contrib/icat-ansible#4]
As noted in icatproject/icat.server#207, the travis build fails because the schema upgrade script is not run. Is there a way to build a string from the version number and look for the matching sql file and run it if it exists?

**Comment by RKrahl** [comment]
This might be somewhat difficult. First of all it would need to automatically detect, if a schema upgrade is needed and which upgrade script is the proper one to run. Then, reading the [install instructions](https://repo.icatproject.org/site/icat/server/4.9.2/installation.html#Schema_upgrade), you will see that not all the upgrades have been straightforward in the past.  Also the naming of the upgrade scripts has not always been consistent.

A simpler approach has been sketched in my comment in icatproject/icat.server#205: If the icat.server integration tests would use `setup install` to deploy, one would only need to make sure either not to install an old version at all or to wipe the icat database before running the test.
