### ISSUE TITLE
The yum module is not compatible with python 3

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject-contrib/icat-ansible#52]
The yum module, used in the `common` role is not compatible with python 3. The [docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html) say to use the [dnf module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html).

I assume we need to change to using the dnf module when we support Python 3, however, I have never used dnf so I am not sure I understand the consequences of installing software using dnf on a system where other software is installed using yum.

**Comment by MRichards99** [comment]
This issue only impacts RedHat machines.

I've discussed this issue with @ajkyffin and we've come to the conclusion that this isn't a problem in real-world use cases. Python 2 won't disappear from Centos/RedHat 7 and Centos/RedHat 8 has Python 2 available (with both yum and dnf to choose from). I'm closing this issue as a result.
