### ISSUE TITLE
Not compatible with Mariadb 10.x

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject-contrib/icat-ansible#56]
The version of mariadb is not pinned so the mariadb role installs the latest version. We could/should pin the version to whichever one we have tested successfully and/or make some changes so that the installation works with Mariadb 10.x. I have found that [this](https://github.com/icatproject-contrib/icat-ansible/blob/master/roles/mariadb/files/mariadb-init) script does not work with mariadb 10.x on Centos 7. We could replace it with individual SQL commands as described [here](https://bertvv.github.io/notes-to-self/2015/11/16/automating-mysql_secure_installation/) or [here](https://stackoverflow.com/questions/24270733/automate-mysql-secure-installation-with-echo-command-via-a-shell-script/35004940).

We may need to make other changes to run on Mariadb 10 on Ubuntu. @kevinphippsstfc reports:

> For me, ICAT failed to deploy with mysql errors about "Specified key was too long"
>
> I found this page:
> [https://srsoftware.de/mariadb-innodb-keycloak](https://srsoftware.de/mariadb-innodb-keycloak)
> 
> and added the following lines to `/etc/mysql/mariadb.conf.d/50-server.cnf` under `[mysqld]`:
```INI
innodb_file_format = Barracuda
innodb_file_per_table = on
innodb_default_row_format = dynamic
innodb_large_prefix = 1
innodb_file_format_max = Barracuda
```

**Comment by MRichards99** [comment]
I've tested Maria 10.3 on a Centos 7 machine and it works. The mariadb role has changed quite a bit since this issue was opened, so I'm not sure this is an issue anymore. As such, I am closing the issue.
